# Site settings
title: Shaun Memon 
description: Welcome to my personal website.
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "http://shaunmemon.com" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Shaun Memon
user_description: I am a recent University of Toronto grad with a B.Sc. specializing in Computer Science. I am looking for software development jobs. My strengths lie in C/C++, systems programming, and low-level programming. I have been programming since highschool and have experience programming in C/C++, Java, Python, JavaScript, Assembly, Scheme (Racket), and even in basic and VisualBasic. I consider myself to by a life long learner and love learning and practicing new skills and solving meaningful problems. I am also interested in product design and management and being involved with products that create meaningful impacts and improve the quality of peoples lives. I would love to be involved in an organization that strives to produce innovative technologies and products for the betterment of business practices and personal livelihood.
user_title: Recent UofT grad with B.Sc. specializing in Computer Science.
email: hello@shaunmemon.com
twitter_username: ShaunMemon
github_username:  m3m0n
# gplus_username:  shaunmemon
linkedin_username: shaunmemon

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
