# Site settings
title: Shaun Memon 
description: Welcome to my personal website.
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "http://shaunmemon.com" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Shaun Memon
user_description: "Thanks for visiting me on the web. I am a life-long learner that relishes every opportunity to learn and gain new skills to solve challenging problems. My interests range from philosophy and personal development, psychology and economics, to neuroscience and technology. 
<BR><BR>
I am a digital marketing professional that helps companies strategically transition through their Agile and digital transformations. 
Today's consumer is more discerning and with shorter attention spans than ever before. Businesses that can quickly adapt to new ways of communicating with their customers by delivering personalized content and creating meaningful connection across disparate channels will be the ones that thrive in the coming decade. My background in technology and marketing creates a unique intersection that positions me to lead teams in adapting to the new digital landscape by leveraging complex marketing technologies and new ways of working.  
<br><br>
My technical strengths lie in analytics, database systems, UNIX systems, mobile first web development, mobile app development, blockchain, numerous programming languages, and low-level systems. I am experienced in research, benchmarking, human-computer interaction, user journey mapping, UI/UX, scrum and Kanban, and leading teams in Agile methodologies.  
<br><br>
The topics I currently find especially salient are:<br>
-    a free and open Internet <br>
-    behavioural economics <br>
-    protecting privacy and freedoms<br>
-    upholding strong democratic values <br>
-    helping people to better manage their lives and finances <br>
-    blockchain and distributed databases <br>"
user_title: Digital Marketing Professional specializing in Enterprise Marketing Technologies and Agile transformations.
email: hello@shaunmemon.com
twitter_username: ShaunMemon
github_username:  m3m0n
insta_username: memonster
spotify_username: sm7800
# gplus_username:  shaunmemon
linkedin_username: shaunmemon

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
