# Site settings
title: Shaun Memon 
description: Welcome to my personal website.
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "http://shaunmemon.com" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Shaun Memon
user_description: "I am a graduate of the University of Toronto specializing in Computer Science. My strengths are in database systems (SQL and NoSQL) and low-level programming with experience in C/C++, Java, Python, JavaScript, Assembly, Scheme (Racket).
<br><br>
I consider myself to be a life long learner and enjoy gaining new skills to solve meaningful problems. My interests lie in working on solutions to problems that lead to an improvement in the quality of peoples lives, the functionality of our societies and social democratic systems.
<br><br>
The principles and technologies which I currently find especially salient are those revolving around preserving a free and open Internet, protecting privacy and liberty, helping people to better manage their lives and finances, blockchain and other distributed databases, embedded systems and low level technology and low level systems programming."
user_title: UofT grad specializing in Computer Science.
email: hello@shaunmemon.com
twitter_username: ShaunMemon
github_username:  m3m0n
insta_username: memonster
# gplus_username:  shaunmemon
linkedin_username: shaunmemon

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
